In [1]:
import numpy as np
import pandas as pd
import os
import sqlite3
import matplotlib.pyplot as plt


In [2]:
#1) Examen
print("Examen")

Examen


In [4]:
#2) Crear un vector de ceros de tamaño 10
vector_ceros = np.zeros(10)
vector_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
vector_ceros = np.zeros(10)
vector_ceros[5]=1
vector_ceros

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [18]:
#4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.
vector_50_elementos = np.arange(51)
vector_50_elementos[::-1]


array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
#5) Crear una matriz de 3 x 3 con valores del cero al 8
matriz_tres_tres = np.arange(9).reshape(3,3)
matriz_tres_tres

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
#6) Encontrar los indices que no sean cero en un arreglo
arreglo = [1,2,0,0,4,0]
arreglo_ar = np.array(arreglo)
arreglo_sin_ceros = (arreglo_ar>0)
arreglo_sin_ceros
arreglo_ar[arreglo_sin_ceros]

array([1, 2, 4])

In [31]:
#7) Crear una matriz de identidad 3 x 3
matriz_identidad_tres_tres = np.eye(3) 
matriz_identidad_tres_tres

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#8) Crear una matriz 3 x 3 x 3 con valores randomicos
matriz_3d_ramdon = np.random.randint(0,27,27).reshape(3,3,3)
matriz_3d_ramdon

array([[[ 9, 26,  0],
        [14, 25,  5],
        [ 3, 25,  1]],

       [[ 1, 21,  8],
        [21, 10, 14],
        [23, 26,  6]],

       [[25, 16, 25],
        [ 2, 17,  3],
        [25, 26, 21]]])

In [39]:
#9) Crear una matriz 10 x 10 y encontrar el mayor y el menor
matriz_10_x_10 = np.arange(100).reshape(10,10)
print("El valor menos es: ")
matriz_10_x_10.min()

El valor menos es: 


0

In [40]:
print("El valor mayor es: ")
matriz_10_x_10.max()

El valor mayor es: 


99

In [49]:
#10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)
from scipy import misc
mapache = misc.face()
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [47]:
#11) ¿Como crear una serie de una lista, diccionario o arreglo?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
mydict

{'a': 0,
 'b': 1,
 'c': 2,
 'e': 3,
 'd': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [52]:
serie = pd.Series(mydict)
serie

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [55]:
#12) ¿Como convertir el indice de una serie en una columna de un DataFrame?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice


In [57]:
index_serie = pd.DataFrame(ser.index)
index_serie

0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

In [63]:
#13) ¿Como combinar varias series para hacer un DataFrame?
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
mix_dataframe = pd.DataFrame({'Columna 1':ser1,'Columna 2':ser2})
mix_dataframe

Columna 1  Columna 2
0          a          0
1          b          1
2          c          2
3          e          3
4          d          4
5          f          5
6          g          6
7          h          7
8          i          8
9          j          9
10         k         10
11         l         11
12         m         12
13         n         13
14         o         14
15         p         15
16         q         16
17         r         17
18         s         18
19         t         19
20         u         20
21         v         21
22         w         22
23         x         23
24         y         24
25         z         25

In [83]:
#14) ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
indices_serie1 = ser1.isin(ser2)
ser1[np.invert(indices_serie1)]


0    1
1    2
2    3
dtype: int64

In [80]:
#15) ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
items_no_comunes1 = pd.Series(list(set(ser1).difference(set(ser2))))
items_no_comunes2 = pd.Series(list(set(ser2).difference(set(ser1))))


0    8
1    6
2    7
dtype: int64

In [81]:
items_no_comunes = pd.concat([items_no_comunes1,items_no_comunes2])
items_no_comunes

0    1
1    2
2    3
0    8
1    6
2    7
dtype: int64

In [99]:
#16) ¿Como obtener el numero de veces que se repite un valor en una serie?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()


e    6
g    5
f    5
d    4
c    4
b    3
h    2
a    1
dtype: int64

In [107]:
#17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
ser

0     1
1     4
2     1
3     1
4     1
5     4
6     2
7     2
8     1
9     2
10    3
11    2
dtype: int32

In [109]:
ser.value_counts()

1    5
2    4
4    2
3    1
dtype: int64

In [122]:
#18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?
ser = pd.Series(np.random.randint(1, 10, 35))
#shape(7,5)
dataframe = pd.DataFrame(ser)
dataframe1 = pd.Series(dataframe.iat[5,7])

IndexError: index 7 is out of bounds for axis 0 with size 1

In [101]:
#19) ¿Obtener los valores de una serie conociendo la posicion por indice?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [125]:
#20) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
#Vertical
pd.DataFrame(ser1,columns = ser2)

ValueError: Shape of passed values is (5, 1), indices imply (5, 5)

In [95]:
#21)¿Obtener la media de una serie agrupada por otra serie?
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['zanahoria', 'manzana', 'banana', 'manzana', 'zanahoria', 'manzana', 'manzana', 'zanahoria', 'manzana', 'banana']


In [88]:
#22)¿Como importar solo columnas especificas de un archivo csv?
data = './BostonHousing.csv'
c=pd.read_csv(data)
df = pd.DataFrame(c)
df = df[["crim","zn"]]
print(df)

         crim    zn
0     0.00632  18.0
1     0.02731   0.0
2     0.02729   0.0
3     0.03237   0.0
4     0.06905   0.0
5     0.02985   0.0
6     0.08829  12.5
7     0.14455  12.5
8     0.21124  12.5
9     0.17004  12.5
10    0.22489  12.5
11    0.11747  12.5
12    0.09378  12.5
13    0.62976   0.0
14    0.63796   0.0
15    0.62739   0.0
16    1.05393   0.0
17    0.78420   0.0
18    0.80271   0.0
19    0.72580   0.0
20    1.25179   0.0
21    0.85204   0.0
22    1.23247   0.0
23    0.98843   0.0
24    0.75026   0.0
25    0.84054   0.0
26    0.67191   0.0
27    0.95577   0.0
28    0.77299   0.0
29    1.00245   0.0
..        ...   ...
476   4.87141   0.0
477  15.02340   0.0
478  10.23300   0.0
479  14.33370   0.0
480   5.82401   0.0
481   5.70818   0.0
482   5.73116   0.0
483   2.81838   0.0
484   2.37857   0.0
485   3.67367   0.0
486   5.69175   0.0
487   4.83567   0.0
488   0.15086   0.0
489   0.18337   0.0
490   0.20746   0.0
491   0.10574   0.0
492   0.11132   0.0
493   0.17331   0.0
