In [2]:
# pip install numpy
import numpy as np

In [6]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
np.zeros([1])

array([0.])

In [9]:
np.zeros((1))

array([0.])

In [11]:
np.zeros([5, 7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.zeros([5, 7, 8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [13]:
np.zeros((5, 7, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [14]:
np.ones([5, 7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
np.arange(4, 20) # [4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(-12, 1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [25]:
arreglo_pares = np.arange(0, 20, 2)

In [24]:
np.arange(-12, 1, 0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5])

In [28]:
print(arreglo_pares.size)
print(len(arreglo_pares))

arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [30]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [32]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [37]:
arreglo_elementos = np.arange(24)
arreglo_elementos.reshape(2,12)
arreglo_elementos.reshape(12,2)
arreglo_elementos.reshape(8,3)
arreglo_elementos.reshape(3,8)
arreglo_elementos.reshape(4,6)
arreglo_elementos.reshape(6,4)
arreglo_elementos.reshape(2,2,3,2)
arreglo_elementos.reshape(2,3,2,2)
arreglo_elementos.reshape(3,2,2,2)
arreglo_elementos.reshape(2,2,2,3)
arreglo_elementos.reshape(2,4,3)
arreglo_elementos.reshape(3,2,4)
arreglo_elementos.reshape(3,4,2)
arreglo_elementos.reshape(2,3,4)
arreglo_elementos.reshape(4,2,3)
arreglo_elementos.reshape(4,3,2)



array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [39]:
a = np.array([10,10,10])
b = np.array([5,5,5])


In [40]:
a + b

array([15, 15, 15])

In [41]:
a - b

array([5, 5, 5])

In [43]:
a * b

array([50, 50, 50])

In [44]:
a / b

array([2., 2., 2.])

In [74]:
x = np.arange(-20,130,5).reshape(3,2,5)
y = np.arange(10,160,5).reshape(3,2,5)

In [75]:
x + y

array([[[-10,   0,  10,  20,  30],
        [ 40,  50,  60,  70,  80]],

       [[ 90, 100, 110, 120, 130],
        [140, 150, 160, 170, 180]],

       [[190, 200, 210, 220, 230],
        [240, 250, 260, 270, 280]]])

In [77]:
x * y

array([[[ -200,  -225,  -200,  -125,     0],
        [  175,   400,   675,  1000,  1375]],

       [[ 1800,  2275,  2800,  3375,  4000],
        [ 4675,  5400,  6175,  7000,  7875]],

       [[ 8800,  9775, 10800, 11875, 13000],
        [14175, 15400, 16675, 18000, 19375]]])

In [78]:
x - y

array([[[-30, -30, -30, -30, -30],
        [-30, -30, -30, -30, -30]],

       [[-30, -30, -30, -30, -30],
        [-30, -30, -30, -30, -30]],

       [[-30, -30, -30, -30, -30],
        [-30, -30, -30, -30, -30]]])

In [80]:
x / y

array([[[-2.        , -1.        , -0.5       , -0.2       ,
          0.        ],
        [ 0.14285714,  0.25      ,  0.33333333,  0.4       ,
          0.45454545]],

       [[ 0.5       ,  0.53846154,  0.57142857,  0.6       ,
          0.625     ],
        [ 0.64705882,  0.66666667,  0.68421053,  0.7       ,
          0.71428571]],

       [[ 0.72727273,  0.73913043,  0.75      ,  0.76      ,
          0.76923077],
        [ 0.77777778,  0.78571429,  0.79310345,  0.8       ,
          0.80645161]]])

In [81]:
a % b

array([0, 0, 0], dtype=int32)

In [82]:
x % y

array([[[  0,   0,  10,  20,   0],
        [  5,  10,  15,  20,  25]],

       [[ 30,  35,  40,  45,  50],
        [ 55,  60,  65,  70,  75]],

       [[ 80,  85,  90,  95, 100],
        [105, 110, 115, 120, 125]]], dtype=int32)

In [85]:
# Multiplicacion
print(a * 10)
# Suma
print(a + 7)
# Resta
print(a - 2)
# Division
print(a / 2)

[100 100 100]
[17 17 17]
[8 8 8]
[5. 5. 5.]


In [186]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

In [88]:
resp = arreglo_muestra > 5

In [89]:
resp

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [91]:
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [187]:
resp = (arreglo_muestra>5) & (arreglo_muestra<12)  
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11])

In [188]:
res

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [191]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [193]:
B = np.arange(4, 8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [195]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [197]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [199]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [201]:
arreglo_doce = np.arange(12)

In [202]:
arreglo_doce.sum()

66

In [203]:
arreglo_doce.min()

0

In [204]:
arreglo_doce.max()

11

In [208]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [210]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [212]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [214]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])