In [9]:
import numpy as np

In [8]:
arreglo_0_a_90_grados = np.array([0,30,45,60,90])

In [10]:
radianes = arreglo_0_a_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [11]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [12]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [13]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [14]:
arreglo_ramdom = np.random.randint(11 #enteros +
                                  )
arreglo_ramdom # [0, 11[

7

In [15]:
arreglo_ramdom = np.random.randint(
    -1,
    2
)
arreglo_ramdom

0

In [16]:
arreglo_ramdom = np.random.randint(
    0, # Minimo
    11, # Maximo
    3 # numero de randomicos
)
arreglo_ramdom

array([3, 9, 5])

In [17]:
np.std(arreglo_ramdom)


2.494438257849294

In [18]:
np.var(arreglo_ramdom)

6.222222222222222

In [19]:
np.mean(arreglo_ramdom)

5.666666666666667